export const locales = ["zh", "en"] as const;
export type Locale = (typeof locales)[number];

export const messages = {
  zh: {
    language: "中文",
    switchToEnglish: "Switch to English",
    switchToChinese: "切换为中文",
    navigation: { posts: "文章", resources: "资源库", submit: "投稿", about: "关于" },
    common: { back: "返回", loading: "加载中…", save: "保存", cancel: "取消", publish: "发布", manage: "管理", uncategorized: "未分类" },
    home: { eyebrow: "分享 · 记录 · 连接", title: "值得长期保存的知识与免费资源。", description: "这里整理学习笔记、实用工具与可靠的开源资源；不收费、不做付费会员，把时间留给真正有价值的内容。", latest: "最新文章", latestHint: "持续更新中", readLatest: "阅读最新文章", learnMore: "了解本站", emptyTitle: "内容正在整理中", emptyDescription: "首批文章和资源会陆续发布。欢迎稍后回来，或从“关于本站”了解这份整理的方向。" },
    resources: { eyebrow: "资源库", title: "免费且值得使用的资源。", description: "优先收录免费工具、开源项目与可靠学习资源，并持续检查链接状态。", recommend: "推荐资源", search: "搜索资源名称或标签…", allCategories: "全部分类", allPricing: "全部价格", allPlatforms: "全部平台", free: "免费", openSource: "开源", freemium: "免费增值", onlyOpenSource: "仅开源", recent: "最近更新", byName: "按名称", filter: "筛选", emptyTitle: "资源正在整理中", emptyDescription: "第一批资源会在审核后发布。你可以先提交一个值得推荐的免费资源。", submit: "提交资源" },
    submit: { eyebrow: "资源投稿", title: "推荐一个值得被发现的资源。", description: "发布前会人工检查资源链接、免费状态与基本信息；审核通过后才会出现在资源库。", name: "资源名称", website: "官网链接", github: "GitHub 链接（可选）", reason: "为什么值得推荐", email: "邮箱（可选，仅在需要确认时联系）", sending: "提交中…", send: "提交审核" },
    resourceDetail: { visit: "访问官网", use: "使用方式", platform: "支持平台", license: "许可证", checked: "最后检查", unmarked: "未标注", pendingCheck: "待检查" },
    resourceCard: { details: "查看详情", visitSite: "访问 {name} 官网", visitGithub: "访问 {name} GitHub" },
    report: { title: "发现资源有问题？", description: "提交后会进入人工处理队列。", websiteBroken: "官网无法访问", downloadBroken: "下载链接失效", githubBroken: "GitHub 链接失效", informationIncorrect: "信息不正确", note: "补充说明（可选）", sending: "提交中…", send: "报告问题" },
    search: { eyebrow: "搜索", title: "寻找文章与资源", placeholder: "输入关键词…", hint: "输入关键词后开始搜索。", posts: "文章", resources: "资源", noPosts: "没有匹配的文章。", noResources: "没有匹配的资源。" },
    footer: { landmark: "页脚", name: "公益资源与博客", description: "长期整理值得使用的免费资源、开源项目与学习记录。", navigation: "导航", information: "说明", home: "首页", contact: "联系", terms: "使用条款", policy: "隐私政策", copyright: "© 2026 公益资源与博客。" },
    login: { title: "登录", email: "邮箱", emailPlaceholder: "你的邮箱", password: "密码", passwordPlaceholder: "密码", signIn: "用邮箱和密码登录", passwordHint: "密码至少需要 6 位", failed: "登录失败：{message}", google: "使用 Google 登录", github: "使用 GitHub 登录" },
    contact: { title: "联系本站", description: "有资源推荐、内容建议或需要反馈的问题，都可以写信告诉我。", name: "称呼", email: "邮箱", message: "内容", send: "发送消息", sent: "消息已发送", failed: "发送失败，请稍后再试。" },
    legal: { termsTitle: "使用条款", terms: ["本站用于公益性质的知识、文章与免费资源分享，不提供付费会员、订阅或商业交易。", "资源链接、介绍与分类仅供参考。使用第三方网站、软件或服务前，请自行阅读其条款和隐私政策，并自行判断风险。", "欢迎转载本站原创内容时注明来源；未经许可，请勿批量复制、镜像或以误导性方式使用本站内容。", "我们会尽力维护链接与信息的准确性，但不保证所有第三方资源始终可访问、免费或适合每个使用场景。", "条款可能随着网站运营需要更新；继续使用本站即表示接受更新后的内容。"], policyTitle: "隐私政策", policyDescription: "本站以尽量少收集信息为原则。", policy: [["我们收集的信息", "当你登录、投稿、反馈资源问题或联系本站时，可能会提供邮箱以及你主动提交的内容。这些信息只用于身份验证、审核、回复和维护网站。"], ["信息的使用与保存", "我们不会出售个人信息，也不会以广告目的追踪访问者。必要的数据由 Supabase 等基础服务在其安全措施下处理和保存。"], ["第三方链接", "资源库会链接到第三方网站。离开本站后，第三方的隐私政策与数据处理方式不受本站控制。"], ["联系我们", "如需询问或删除你主动提交的信息，请通过联系页面发送消息。"]] },
    dashboard: { posts: "文章", bookmarks: "收藏", settings: "设置", profile: "个人资料", signOut: "退出登录", closeSidebar: "关闭侧边栏", avatar: "头像" },
    admin: { eyebrow: "管理员", reviews: "审核队列", publishPost: "发布文章", managePosts: "管理文章", publishResource: "发布资源", manageResources: "管理资源", postManager: "文章管理", postManagerHint: "可查看发布状态，并随时下架或重新发布文章。", resourceManager: "资源管理", resourceManagerHint: "修改资源状态会同步影响前台资源库。", loadingPosts: "正在读取文章…", noPosts: "还没有文章。可先发布第一篇。", postsUnavailable: "暂时无法读取文章；稍后刷新即可重试。", loadingResources: "正在读取资源…", noResources: "还没有已发布资源。", resourcesUnavailable: "暂时无法读取资源；稍后刷新即可重试。", published: "已发布", unpublished: "已下架", unpublish: "下架", republish: "重新发布", status: "状态", lastChecked: "最后检查", unchecked: "未检查", active: "正常", broken: "失效", archived: "归档", loadingQueue: "正在读取审核队列…", queueUnavailable: "暂时无法读取审核队列", queueUnavailableHint: "数据库连接较慢；页面已可使用，稍后刷新即可重试。", submissions: "资源投稿", reports: "失效反馈", approveAndPublish: "通过并发布", reject: "拒绝", noSubmissions: "没有待审核投稿。", noReports: "没有待处理反馈。", deletedResource: "已删除资源", markResolved: "标记已处理" },
    adminForm: { newPostHint: "先用这个稳定的基础编辑入口发布内容；富文本、封面和标签会在下一阶段统一完善。", savePostError: "保存失败。请检查标题、英文网址名、摘要和正文；网址名不能重复。", saveResourceError: "保存失败：请检查必填项、链接和 slug 是否正确。", title: "标题", slug: "网址名（英文）", category: "分类", description: "摘要", body: "正文", bodyPlaceholder: "直接输入文章内容；空一行会成为新段落。", name: "名称", resourceDescription: "简介", pricing: "使用方式", website: "官网", github: "GitHub", platform: "平台", license: "许可证（可选）", tags: "标签（可选，以逗号分隔）" },
    about: { eyebrow: "关于本站", title: "把值得使用的免费资源，认真地整理出来。", description: "这里记录学习与实践，也长期筛选免费工具、开源项目和可靠的线上资源。", features: [["认真筛选", "优先收录明确免费、长期可用且来源可靠的内容，不追求资源数量。"], ["保持透明", "资源会显示链接、分类与检查日期；发现失效或信息错误时，可以直接反馈。"], ["开放分享", "欢迎提交值得被更多人看见的免费工具、项目和学习资源，由管理员审核后发布。"], ["长期维护", "内容与设计都以长期阅读和使用为目标，尽量避免短期潮流带来的负担。"]] },
  },
  en: {
    language: "English",
    switchToEnglish: "Switch to English",
    switchToChinese: "Switch to Chinese",
    navigation: { posts: "Posts", resources: "Resources", submit: "Submit", about: "About" },
    common: { back: "Back", loading: "Loading…", save: "Save", cancel: "Cancel", publish: "Publish", manage: "Manage", uncategorized: "Uncategorized" },
    home: { eyebrow: "Share · Notes · Links", title: "Knowledge and free resources worth keeping.", description: "A carefully maintained collection of notes, practical tools and reliable open-source resources — no fees or paid memberships.", latest: "Latest articles", latestHint: "Updated regularly", readLatest: "Read latest articles", learnMore: "About this site", emptyTitle: "Content is being prepared", emptyDescription: "The first articles and resources will be published soon. Please check back later, or learn what this site is for." },
    resources: { eyebrow: "Resources", title: "Free resources worth using.", description: "A curated directory of free tools, open-source projects and dependable learning resources, with links checked regularly.", recommend: "Recommend a resource", search: "Search names or tags…", allCategories: "All categories", allPricing: "All pricing", allPlatforms: "All platforms", free: "Free", openSource: "Open source", freemium: "Freemium", onlyOpenSource: "Open source only", recent: "Recently updated", byName: "By name", filter: "Filter", emptyTitle: "Resources are being prepared", emptyDescription: "The first collection will be published after review. You can recommend a valuable free resource now.", submit: "Submit a resource" },
    submit: { eyebrow: "Submit a resource", title: "Recommend something worth discovering.", description: "Links, free availability and basic information are reviewed before publication.", name: "Resource name", website: "Website", github: "GitHub link (optional)", reason: "Why is it worth recommending?", email: "Email (optional, only for follow-up)", sending: "Submitting…", send: "Submit for review" },
    resourceDetail: { visit: "Visit website", use: "Availability", platform: "Platforms", license: "License", checked: "Last checked", unmarked: "Not specified", pendingCheck: "Pending check" },
    resourceCard: { details: "View details", visitSite: "Visit {name} website", visitGithub: "Visit {name} on GitHub" },
    report: { title: "Found a problem with this resource?", description: "Your report will enter the review queue.", websiteBroken: "Website unavailable", downloadBroken: "Download link is broken", githubBroken: "GitHub link is broken", informationIncorrect: "Information is incorrect", note: "Additional details (optional)", sending: "Sending…", send: "Report issue" },
    search: { eyebrow: "Search", title: "Find articles and resources", placeholder: "Enter a keyword…", hint: "Enter a keyword to start searching.", posts: "Articles", resources: "Resources", noPosts: "No matching articles.", noResources: "No matching resources." },
    footer: { landmark: "Footer", name: "Public Resources & Blog", description: "A long-term collection of useful free resources, open-source projects and learning notes.", navigation: "Navigation", information: "Information", home: "Home", contact: "Contact", terms: "Terms of use", policy: "Privacy policy", copyright: "© 2026 Public Resources & Blog." },
    login: { title: "Sign in", email: "Email", emailPlaceholder: "Your email", password: "Password", passwordPlaceholder: "Password", signIn: "Sign in with email and password", passwordHint: "Password must be at least 6 characters", failed: "Sign-in failed: {message}", google: "Sign in with Google", github: "Sign in with GitHub" },
    contact: { title: "Contact", description: "Send a note with a resource recommendation, content suggestion or issue to report.", name: "Name", email: "Email", message: "Message", send: "Send message", sent: "Message sent", failed: "Could not send the message. Please try again later." },
    legal: { termsTitle: "Terms of use", terms: ["This is a nonprofit site for sharing knowledge, articles and free resources. It does not offer paid memberships, subscriptions or commercial transactions.", "Resource links, descriptions and categories are for reference. Before using a third-party site, app or service, review its terms and privacy policy and assess the risk yourself.", "When reposting original material from this site, please credit the source. Do not copy, mirror or use the content in a misleading way without permission.", "We work to keep links and information accurate, but cannot guarantee that every third-party resource will remain accessible, free or suitable for every purpose.", "These terms may be updated as the site evolves. Continued use means you accept the current version."], policyTitle: "Privacy policy", policyDescription: "This site is designed to collect as little personal information as possible.", policy: [["Information we collect", "When you sign in, submit a resource, report an issue or contact the site, you may provide an email address and content you choose to send. This is used only for authentication, review, replies and site maintenance."], ["How information is used and stored", "We do not sell personal information or track visitors for advertising. Necessary data is handled and stored by foundational services such as Supabase under their security measures."], ["Third-party links", "The directory links to third-party websites. Once you leave this site, their privacy policies and data practices are outside our control."], ["Contact", "To ask about or delete information you submitted, send a message through the contact page."]] },
    dashboard: { posts: "Posts", bookmarks: "Bookmarks", settings: "Settings", profile: "Profile", signOut: "Sign out", closeSidebar: "Close sidebar", avatar: "Avatar" },
    admin: { eyebrow: "Admin", reviews: "Review queue", publishPost: "Publish article", managePosts: "Manage articles", publishResource: "Publish resource", manageResources: "Manage resources", postManager: "Article management", postManagerHint: "Review publishing status, and unpublish or republish articles at any time.", resourceManager: "Resource management", resourceManagerHint: "Changing a resource status also changes its visibility in the public directory.", loadingPosts: "Loading articles…", noPosts: "No articles yet. Publish the first one.", postsUnavailable: "Articles cannot be loaded right now. Refresh to try again.", loadingResources: "Loading resources…", noResources: "No published resources yet.", resourcesUnavailable: "Resources cannot be loaded right now. Refresh to try again.", published: "Published", unpublished: "Unpublished", unpublish: "Unpublish", republish: "Republish", status: "Status", lastChecked: "Last checked", unchecked: "Not checked", active: "Active", broken: "Broken", archived: "Archived", loadingQueue: "Loading review queue…", queueUnavailable: "Review queue is unavailable", queueUnavailableHint: "The database connection is slow. The page remains usable; refresh to try again.", submissions: "Resource submissions", reports: "Broken-link reports", approveAndPublish: "Approve and publish", reject: "Reject", noSubmissions: "No submissions to review.", noReports: "No reports to review.", deletedResource: "Deleted resource", markResolved: "Mark resolved" },
    adminForm: { newPostHint: "Use this reliable editor to publish content now; rich text, cover images and tags will be refined together in the next phase.", savePostError: "Could not save. Check the title, URL slug, summary and body; the slug must be unique.", saveResourceError: "Could not save. Check required fields, URLs and the slug.", title: "Title", slug: "URL slug", category: "Category", description: "Summary", body: "Body", bodyPlaceholder: "Enter the article text directly; a blank line starts a new paragraph.", name: "Name", resourceDescription: "Description", pricing: "Availability", website: "Website", github: "GitHub", platform: "Platforms", license: "License (optional)", tags: "Tags (optional, comma-separated)" },
    about: { eyebrow: "About", title: "A carefully maintained directory of free resources.", description: "This is a long-term collection of learning notes, practical tools, open-source projects and reliable online resources.", features: [["Carefully curated", "Only genuinely free, dependable and useful resources are included — quantity is not the goal."], ["Transparent", "Resources show their links, categories and check dates, and anyone can report an issue."], ["Open sharing", "Useful free tools, projects and learning resources can be submitted for review."], ["Built to last", "Both content and design are made for long-term reading and use, not short-lived trends."]] },
  },
} as const;

export const isLocale = (value: string | undefined): value is Locale =>
  Boolean(value && locales.includes(value as Locale));
