import { createResource } from "@/actions/admin/create-resource";
import { getRequestLocale } from "@/lib/i18n-server";
import { messages } from "@/lib/i18n";

export default async function NewResourcePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  const allCopy = messages[await getRequestLocale()];
  const copy = allCopy.admin;
  const formCopy = allCopy.adminForm;
  return <main className="mx-auto max-w-3xl px-6 py-10"><p className="text-sm font-medium tracking-[0.16em] text-primary uppercase">{copy.eyebrow}</p><h1 className="mt-3 text-3xl font-bold tracking-tight">{copy.publishResource}</h1>
    {error ? <p className="mt-5 rounded-xl border border-destructive/25 bg-destructive/5 p-3 text-sm text-destructive">{formCopy.saveResourceError}</p> : null}
    <form action={createResource} className="mt-8 grid gap-5 rounded-2xl border border-border bg-card p-6">
      <div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">{formCopy.name}<input required name="name" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label><label className="grid gap-2 text-sm font-medium">{formCopy.slug}<input required name="slug" placeholder="github" pattern="[a-z0-9-]+" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label></div>
      <label className="grid gap-2 text-sm font-medium">{formCopy.resourceDescription}<textarea required name="description" minLength={20} rows={4} className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label>
      <div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">{formCopy.category}<input required name="category" placeholder="开发工具" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label><label className="grid gap-2 text-sm font-medium">{formCopy.resourceType}<select name="resourceType" defaultValue="website" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal"><option value="website">{formCopy.types.website}</option><option value="open_source">{formCopy.types.open_source}</option><option value="download">{formCopy.types.download}</option><option value="document">{formCopy.types.document}</option><option value="template">{formCopy.types.template}</option><option value="asset">{formCopy.types.asset}</option><option value="api">{formCopy.types.api}</option><option value="service">{formCopy.types.service}</option></select></label></div>
      <label className="grid gap-2 text-sm font-medium">{formCopy.pricing}<select name="pricing" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal"><option value="free">{allCopy.resources.free}</option><option value="open_source">{allCopy.resources.openSource}</option><option value="freemium">{allCopy.resources.freemium}</option></select></label>
      <div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">{formCopy.website}<input name="website" type="url" placeholder="https://" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label><label className="grid gap-2 text-sm font-medium">{formCopy.github}<input name="github" type="url" placeholder="https://github.com/..." className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label></div>
      <label className="grid gap-2 text-sm font-medium">{formCopy.externalDownload}<input name="download" type="url" placeholder="https://example.com/download" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label>
      <label className="grid gap-2 text-sm font-medium">{formCopy.attachment}<input name="attachment" type="file" accept=".pdf,.zip,.txt,.jpg,.jpeg,.png,.webp,application/pdf,application/zip,text/plain,image/jpeg,image/png,image/webp" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal file:mr-4 file:border-0 file:bg-transparent file:text-sm file:font-semibold" /><span className="text-xs font-normal leading-5 text-muted-foreground">{formCopy.attachmentHint}</span></label>
      <div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">{formCopy.platform}<input name="platform" placeholder="Web, macOS, Windows" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label><label className="grid gap-2 text-sm font-medium">{formCopy.license}<input name="license" placeholder="MIT" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label></div>
      <label className="grid gap-2 text-sm font-medium">{formCopy.tags}<input name="tags" placeholder="效率, 开源, 开发工具" className="rounded-xl border border-input bg-background px-3 py-2.5 font-normal" /></label>
      <button className="w-fit rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">{copy.publishResource}</button>
    </form></main>;
}
